[meta]
  title = "Prerecorded Flask Starter"
  description = "Basic demo for using Deepgram to transcribe files with Flask"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "Prerecorded"
  language = "Python"
  framework = "Flask"

[build]
  command = "pip install -r requirements.txt"

[config]
  sample = "sample.env"
  output = ".env"

[post-build]
  message = "Run `flask run -p 8080` to get up and running."